apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vote-ui
  template:
    metadata:
      labels:
        app: vote-ui  # Ensure that these labels match the labels in the selector
    spec:
      containers:
      - name: vote-ui
        image: nginx  # Replace with your desired container image
        ports:
        - containerPort: 80

